name: Main
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run cmake
        run: cmake .
      - name: Build project
        run: make
      - name: Run tests
        run: make test
