name: Main
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Some CI debug stuff
        run: ls -lah . && ls -lah ../
      - name: Run cmake
        run: cmake .
      - name: Build project
        run: make
      - name: Run tests
        run: make test
